### PR TITLE
T add user bill and apartment submission request

### LINKED ISSUE #26: Create routes to allow the Mobile and Client to access the api.
## The Issue
This issue builds in links to be able to CRUD data from the database, this will have routes that will allow users to access and change information from the client app and the mobile app. 

### To-do
- [x] Bills
  - [x] Allow a `user` to create a bill.
  - [x] Allow a `user` to assign the bill to other users.
  - [x] A `user` should be able to see the bill that are associated with them. 
  - [x] A `user` should be able to accept a bill associated with them.
  - [x] A `user` should be able to pay a bill associated with them. 

- [x] Apartments
  - [x] Allow a `user` to create an `apartment`.
  - [x] Allow a `user` to join the `apartment`.
  - [x] A `user` should be able to view details of the `apartment`. 
  - [x] A `user` should be able to leave an `apartment`
  - [x] A `associated user` should be able to delete the apartment.

### PR DESCRIPTION
**Pull request by jhibbeard89**
**Related Issue**
closes #26 

### Changes and Updates

- Added two migrations to add user to the bills and apartments
- Updated the Models to create a relationship to the users. 

### Added APIs, Webpack or Yarn/NPM installs

- _No Added APIs_

### Notes

- _No notes_

### CODE REVIEW

**Comment by jhibbeard89** [comment]
## Close 01.01.22

Created new tests and functionality with the API to be able to add, get and update apartment and bill information, this will be continued tomorrow. 

Should be ready to merge into main on 02.01

**Comment by jhibbeard89** [comment]
## close 02.01

Integrated the user being able to retrieve their apartment and bills, the user now only needs to be able to delete and remove themselves from an apartment. This should be completed tomorrow morning.

**Comment by jhibbeard89** [comment]
## Finished 

All updates have been completed and it is now ready for merging into main. @AdamTomczyk 😄

**Review by AdamTomczyk — APPROVED** [review]
Looks all good 👨🏻

**Pull request merged**
