### PR TITLE
T db seed creation

### PR DESCRIPTION
**Pull request by jhibbeard89**
### Changes and Updates

- removed reference columns from apartment and bills
- Added additional reference column to apartment_user table
- created Seed Files
- Added Tests to check new tables. 

### Notes

- If last version was download then drop db and create again, this has not yet gone to production and some migration files have been updated.

### CODE REVIEW

**Comment by jhibbeard89** [comment]
## Close 10.12

- Added modal for user_bills, apartment_bills and user_apartments
- Added tests to test for users, apartments and bills

## To-do

- [ ] Build tests for Apartments and bills. 
- [ ] Finish testing the link between each table.

**Comment by jhibbeard89** [comment]
@valentinLW If all is done it is now ready to be checked and approved.

**Comment by jhibbeard89** [comment]
@valentinLW It's now ready for review, seed files have been created

**Review by valentinLW — COMMENTED** [review]
Looks good to me

**Pull request merged**
